### ISSUE TITLE
Post Request To Api

### ISSUE THREAD

**Issue by KhushC-03** [mozilla-services/requests-hawk#30]
How am I meant to post request to an API which does not provide a secret key or session token. The only info available is the ID,

**Comment by Natim** [comment]
For which service? Do you have a link to the documentation or implementation?

If there is no secret there is no hawk signature. At Mozilla we use a session token from which we derivate both the ID and the password to sign the request.

**Comment by KhushC-03** [comment]
in order to communicate with the API, it also requires googles Recaptcha.
the authorization header looks like this 'Hawk id="e27d1ea0", mac="gciSdjuzSzb8TkdjCGoiJIstSsGAW/jnRNAhFTOIeTk=", ts="1613411319", nonce="6f8460", hash="54d84b483fa8f25355d049b35ff8ec6c90bfeda6ed7b43278cec74d003ff4aec"'

**Comment by Natim** [comment]
If you only have the header you cannot generate a signature that's the point of Hawk.

**Comment by KhushC-03** [comment]
It's an API I've been told to add. but have been given 0 documentation. there are some strings from other request responses that could be session tokens. I've also looked at the requests via third party software to try and figure out how or where the necessary information comes from.

**Comment by jrconlin** [comment]
It might be worth spending some time learning about HAWK, then. Here's the general write up: https://github.com/mozilla/hawk/blob/main/API.md 

Some cautions: 
1) HAWK is currently in maintenance mode. That means that no new features will be worked on and mostly it's there to support existing services that use HAWK Authentication.
2) HAWK has an... interesting... history, since it was developed as a reaction to OAuth 2, by the author of OAuth 1. HAWK provides reasonable security when properly used, but like any security mechanism, there are lots of opportunities to get it wrong. 

As a developer, your responsibility is the security of the system that you're building. One of the long standing issues of HAWK is that it doesn't have a good deal of documentation, (although there are [blog posts](https://blog.notmyidea.org/whats-hawk-and-how-to-use-it.html) that can help explain it better) which means that it's up to you to understand and learn. Unless you're comfortable with using it, I would probably suggest using a different, more well-used authentication system like OAuth 2. It's far from perfect as well, but there are lots of books, tutorials and libraries that implement it and it's learning curve is a bit more shallow.
